### ISSUE TITLE
LineaGoerli to Goerli

### ISSUE THREAD

**Issue by LawlessIntegrayshun30** [Consensys/doc.linea#248]
The LineaGeorli to Linea Bridge as outlined here:

https://docs.linea.build/build-on-linea/use-linea-testnet/bridge-funds/usdc-bridge#linea-goerli-to-goerli

has the Bridge contract address as this:
0xA59477f7742Ba7d51bb1E487a8540aB339d6801d
https://goerli.lineascan.build/address/0xa59477f7742ba7d51bb1e487a8540ab339d6801d

The docs say to utilize the proxy version for interaction but the proxy version isn't available at that address.  According to the fancy scan site, this is due to the implementation contract not being verified:

(Imp. Cont.)
0xC440D64b826c2707DC982ca55162d5609cE3f203
https://goerli.lineascan.build/address/0xc440d64b826c2707dc982ca55162d5609ce3f203#code

However, there are links to similar contracts but I think those are for other ERC20 tokens, although I could be wrong.  I mean if all of the info is there, I guess I could verify the contract, but I would hate to try and win and piss someone off or try and fail but send a message to God that pisses someone off, so...maybe someone can fix it.  Or tell me what to do and I'll fix it...thanks

**Comment by bgravenorst** [comment]
Issue is over a year old and Goerli is no longer active.
