### ISSUE TITLE
npm i -D @truffle/hdwallet-provider throws an error

### ISSUE THREAD

**Issue by roo-shy** [Consensys/doc.linea#27]
## `npm i -D @truffle/hdwallet-provider` throws an error

Multiple people reported an error message when using `npm i -D @truffle/hdwallet-provider` 
`npm i @truffle/hdwallet-provider` works fine. 

There are 2 times where it is asked to install @truffle/hdwallet-provider : 
<img width="644" alt="Screen Shot 2023-03-15 at 11 10 28 AM" src="https://user-images.githubusercontent.com/13618162/225278434-d656064c-721e-4cb1-a22f-4d669e92d175.png">
<img width="640" alt="Screen Shot 2023-03-15 at 11 10 36 AM" src="https://user-images.githubusercontent.com/13618162/225278430-83c8b666-0e41-42d3-a2a4-bbb8bda9335a.png">

**Comment by mujahid002** [comment]
Try this:  **npm i @truffle/hdwallet-provider@next**
It worked for me!

**Comment by bgravenorst** [comment]
Closing because Truffle is no longer supported.
