### ISSUE TITLE
Add quickstart instructions for Remix

### ISSUE THREAD

**Issue by emilyJLin95** [Consensys/doc.linea#31]

**Comment by AnmolSirola** [comment]
@emilyJLin95 Can you tell me more a about this issue and how to fix it. I am interested :)

**Comment by emilyJLin95** [comment]
So similar to how we do the deployment instructions for truffle, hardhat, foundry (https://docs.linea.build/build-on-linea/quickstart/deploy-smart-contract/hardhat)

Giving instructions on how to deploy on Linea using Remix
