### ISSUE TITLE
Broken links in Linea docs

### ISSUE THREAD

**Issue by KyryloKilin** [Consensys/doc.linea#359]
1. A broken link on the page: https://docs.linea.build/use-mainnet/info-contracts#network-information 
![image](https://github.com/Consensys/doc.zk-evm/assets/83702309/600d987a-ea0c-4bc9-8604-d158c3d3b76f)

2. A broken link on the page: https://docs.linea.build/use-mainnet/info-contracts#network-information 
![image](https://github.com/Consensys/doc.zk-evm/assets/83702309/3f6aefbd-a32b-4406-9a15-bb9f9efc84d0)

3. A broken link on the page: https://docs.linea.build/build-on-linea/quickstart/deploy-smart-contract/thirdweb#create-a-smart-contract
![image](https://github.com/Consensys/doc.zk-evm/assets/83702309/4cd57ac4-e2d0-4731-88d0-e82eb153d667)

4. A broken link on the page: https://docs.linea.build/build-on-linea/tooling/libraries/wagmi
![image](https://github.com/Consensys/doc.zk-evm/assets/83702309/8063756d-5e0c-4fbb-8293-1db55f6399f6)

**Comment by Matttioboy** [comment]
well spotted thank you

**Comment by jlwllmr** [comment]
@KyryloKilin thanks for this. I'll be closing since:
- The first two are RPC endpoints, which are not meant to link to webpages, so may appear 'broken'. They don't require updates.
- The second two have seemingly been fixed since you created the issue.
