### ISSUE TITLE
Add more bridges to linea 

### ISSUE THREAD

**Issue by charming1** [Consensys/doc.linea#427]
add more bridges to linea network especially bridges attached with wormhole

**Comment by Goiji** [comment]
Owlto and Orbiter are work for me.

**Comment by jlwllmr** [comment]
Hey @charming1, all the available bridges can be found [here](https://linea.build/apps). You can also use the [MetaMask bridge](https://portfolio.metamask.io/bridge), which aggregates various bridges.
