### ISSUE TITLE
Add Arcana updates to Linea docs

### ISSUE THREAD

**Issue by shaloo** [Consensys/doc.linea#453]
Arcana wallet comes pre-configured with Linea.  Web3 apps that integrate with the Arcana Auth SDKs allow users to instantly access Arcana wallet from within the app context and begin signing blockchain transactions. No need to install any browser extension. Plus it also supports gasless.

**Comment by greghfield** [comment]
Extension haven’t always been the most secure either. I agree Linea Eco needs their own Wallet.

**Comment by shaloo** [comment]
Info about how to integrate Arcana wallet in Web3 apps is now available in Linea docs - closing this ticket.
See: 
1. Social Login for Web3: https://docs.linea.build/developers/tooling/social-login/arcana
2. AA and Gasless Transactions: https://docs.linea.build/developers/tooling/account-abstraction/arcana
