### ISSUE TITLE
Clarify gas estimation

### ISSUE THREAD

**Issue by kaber2** [Consensys/doc.linea#530]
I'm trying to understand how exactly the gas use is calculated. I've checked LineaEstimateGas.java, however I couldn't find anything related to how L1 fees are calculated and factored in.

Could you please provide the formula used to go from pure L2 gas use to total gas use including L1?

Thanks!

**Comment by zealousFred** [comment]
Would also like to know...

**Comment by kaber2** [comment]
Don't hold your breath.

Given that linea_estimateGas has been "temporarily deactivated" and the apparent unwillingness to give out simple information required to properly use this chain, I have to conclude that this chain is not properly operated and will therefore deactivate my nodes and stop wasting my time here.

**Comment by dfox-consensys** [comment]
Currently, gas is metered the same as Ethereum (London HF) and gas price is calculated using the standard API's: eth_feeHistory, eth_gasPrice

The L1 cost is not calculated in the L2 gas price, rather the L1L2ratio is determined such that the price presented will cover the overhead of posting to L1. The sequencer runs a check for tx inclusion that prevents unprofitable transactions being included.

linea_estimateGas (not active yet) will include multi-dimensional pricing such that the calldata present in the L2 tx is considered and therefore L2 txs that have a smaller L1 DA footprint will be priced lower on L2. When the API is finalized and activated for usage, it will include more info about how the L2 gas price is calculated.
