### ISSUE TITLE
Verb tense mistake in the readme documentation

### ISSUE THREAD

**Issue by govardhan666** [Consensys/doc.linea#721]
### Describe the bug

Wrong verb tense is used in the readme documentation
Original sentence: "It's possible that you **will** use a word in your content that is not known to the linter, and your build, or commit, will fail."
Corrected sentence: "It's possible that you **might** use a word in your content that is not known to the linter, and your build, or commit, will fail."

### Steps to reproduce

None, simple typing error.

### Expected behavior

None, simple typing error.

**Comment by jlwllmr** [comment]
thanks @govardhan666. I don't think is an error as such—both statements are valid grammar and make sense, unless I'm missing something—but I'll add a fix given I think your suggestion is an improvement in any case, and reads more naturally.

**Comment by govardhan666** [comment]
Thank you for considering my suggestion.
