### ISSUE TITLE
Update WalletConnect page to Reown

### ISSUE THREAD

**Issue by jlwllmr** [Consensys/doc.linea#833]
### Describe the bug

WalletConnect is now [Reown](https://reown.com/). 

The page is out-of-date and needs some attention.

### Steps to reproduce

n/a

### Expected behavior

n/a

### Link(s)

https://docs.linea.build/developers/tooling/libraries/wallet-connect

**Comment by qvkare** [comment]
I passed an update for it https://github.com/Consensys/doc.linea/pull/887#issue-2724467229

**Comment by qvkare** [comment]
I had a problem with my node branch, I was going to recreate it over the weekend, but I didn't need to, great job thanks. @jlwllmr

**Comment by jlwllmr** [comment]
@qvkare no problem, I assumed you just got frustrated by my requests for changes, and would have left it for you if I knew you were returning to it 😅  but thanks for your time on this one!
