### ISSUE TITLE
Correct `cURL` to `curl`

### ISSUE THREAD

**Issue by jlwllmr** [Consensys/doc.linea#866]
### Describe the bug

The official [curl site](https://curl.se/) uses the lowercase option, suggesting `cURL` ([still used by Wikipedia](https://en.wikipedia.org/wiki/CURL)) is outdated (although Wikipedia does suggest the command line tool we're referring to is `curl`, and `cURL` is just the name of the wider project. We should adjust all occurences of it. 

### Steps to reproduce

n/a

### Expected behavior

`curl` rather than `cURL`

**Comment by ChinoUkaegbu** [comment]
Hi, I'd like to work on this! Just to clarify, the changes will be made to all files returned in this [search](https://github.com/search?q=repo%3AConsensys%2Fdoc.linea+%2F%28%3F-i%29cURL%2F&type=code)?

**Comment by jlwllmr** [comment]
fixed in #868 

@ChinoUkaegbu sorry for not getting to your comment in time!
