### ISSUE TITLE
Update config to use host-allowlist

### ISSUE THREAD

**Issue by macfarla** [Consensys/doc.linea#873]
### Describe the bug

This config file needs to be updated to use host-allowlist in place of host-whitelist

### Steps to reproduce

https://github.com/Consensys/doc.linea/blob/e5012338cf6635b584396940f7c7b86a4f45ec78/static/files/besu/config-sepolia.toml#L22

### Expected behavior

This is an upcoming breaking change in Besu https://github.com/hyperledger/besu/issues/7761

**Comment by jlwllmr** [comment]
thank you for flagging @macfarla!
